# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-10 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('r', 'Waiting processes'), ('b', 'Sleeping processes'), ('swpd', 'Virtual memory'), ('free', 'Idle memory'), ('buff', 'Memory used as buffers'), ('cache', 'Memory used as cache'), ('inact', 'Inactive memory'), ('active', 'Active memory'), ('si', 'Memory swapped in'), ('so', 'Memory swapped out'), ('bi', 'IO (in)'), ('bo', 'IO (out)'), ('in', 'System interrupts per second'), ('cs', 'Context switches per second'), ('us', 'CPU User time'), ('sy', 'CPU System time'), ('id', 'CPU Idle time'), ('wa', 'CPU IO wait time'), ('st', 'CPU Stolen from a virtual machine time')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('warmup', 'Warm-Up'), ('steady', 'Steady'), ('pressure', 'Under Pressure'), ('stress', 'Stress'), ('thrashing', 'Thrashing')], default='warmup', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='datalist',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_list', to='service.Server'),
        ),
        migrations.AddField(
            model_name='data',
            name='data_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='service.DataList'),
        ),
        migrations.AlterUniqueTogether(
            name='datalist',
            unique_together=set([('server', 'attribute')]),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together=set([('data_list', 'timestamp')]),
        ),
    ]
