# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_server_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='attribute',
            field=models.CharField(choices=[('r', 'Waiting processes'), ('b', 'Sleeping processes'), ('swpd', 'Virtual memory'), ('free', 'Idle memory'), ('buff', 'Memory used as buffers'), ('cache', 'Memory used as cache'), ('si', 'Memory swapped in'), ('so', 'Memory swapped out'), ('bi', 'IO (in)'), ('bo', 'IO (out)'), ('in', 'System interrupts per second'), ('cs', 'Context switches per second'), ('us', 'CPU User time'), ('sy', 'CPU System time'), ('id', 'CPU Idle time'), ('wa', 'CPU IO wait time'), ('st', 'CPU Stolen from a virtual machine time')], max_length=8),
        ),
    ]
