# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20170803_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='user_name',
            field=models.CharField(default='root', max_length=128),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(default='localhost', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together=set([('data_list', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='datalist',
            unique_together=set([('server', 'attribute')]),
        ),
    ]
