# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20170807_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='server',
            name='user_name',
            field=models.CharField(max_length=128),
        ),
    ]
